# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  publish-to-marketplace:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the tag on this image to a more stable version, using latest can result in unstable builds.
    docker:
      - image: cimg/node:16.13.1 #current lts
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          working_directory: .
          name: Install packages
          command: |
            yarn install
      - run:
          working_directory: .
          name: Package extension
          command: |
            yarn run vsce package
      - run:
          working_directory: .
          name: Publish extension
          command: |
            yarn run vsce publish
      
workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  build-and-publish:
    jobs:
      - publish-to-marketplace:
          filters: 
            branches:
              only: master
          context: "Main context"